name: deploy-server

on:
  workflow_dispatch:
  push:
    paths:
      - server/**
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest 
    container:
      image: node:20 
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      
      - name: Get SSH Key and set permissions
        run:
          mkdir -p ~/ .ssh
          echo "${secrets startaenXX" > ~/.ssh/id_rsa && chmod 600 ~/. ssh/id_rsa
          
      - name: Deploy using SCP
        run: scp -o StrictHostKeyChecking=no -1 ~/-ssh/id_rsa-r•/dist/* Stisecrets. SSH USER West secrets. SSH HOST: ~/node-app
        
      - name: Restart Server
        run: ssh -o StrictHostKeyChecking=no -i ~/ssh/id_rsa Stsecrets SSH USER MOSt secrets SSH HOSTU
