name: Deploy Client
on:
  workflow_dispatch:
  push:
    paths:
      - client/**
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Generate version
        run: echo "version=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          APP_VERSION=${{ steps.version.outputs.version }} \
          npm run build

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: "--prod" # Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required
