name: deploy-client

on:
  workflow_dispatch:
  push:
    paths:
      - client/**
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: cd client
      
      - id: npm-install
        name: Install Node Modules
        run: npm ci

      - id: lint
        name: Lint Project
        run: npm run lint

      - id: npm-run-build
        name: Build Project
        run: npm run build

      - id: aws-config-creds
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - id: deploy-dist-to-s3
        name: Deploy dist/ folder to s3
        run: |
          aws s3 sync ./dist/ s3://las-costas-site
