name: Deploy Client
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    paths:
      - client/**
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Generate version
        run: echo "version=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          APP_VERSION=${{ steps.version.outputs.version }} \
          npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
