name: deploy-server

on:
  workflow_dispatch:
  push:
    paths:
      - server/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20

      - run: ls -la
      - run: npm ci
      - run: npm run build

      - name: Clean up folders
        run: rm -rf dist && rm -rf node_modules

      - name: Get SSH key and set permissions
        run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Copy server code to EC2
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/las-costas

      - name: SSH into EC2
        run: ssh -o StrictHostKeyChecking=no -i ~/ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Setup and restart server
        run: cd ~/las-costas && npm run install && npm run build && pm2 restart 0
